import { NextRequest, NextResponse } from "next/server"
import { getServiceSupabase } from "@/lib/supabase"

/**
 * POST /api/registrations
 * Creates a new delegate record with payment_status = 'pending'.
 * The delegate_id is auto-generated by the database trigger (SMUN-DEL-XXXX).
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { name, email, phone, institution, committee_pref, country_pref } = body

    // Server-side validation
    if (!name?.trim() || !email?.trim() || !phone?.trim() || !institution?.trim() || !committee_pref?.trim() || !country_pref?.trim()) {
      return NextResponse.json({ error: "All fields are required." }, { status: 400 })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: "Invalid email format." }, { status: 400 })
    }

    const phoneClean = phone.replace(/\s/g, "")
    if (!/^\+?\d{10,15}$/.test(phoneClean)) {
      return NextResponse.json({ error: "Invalid phone number." }, { status: 400 })
    }

    const supabase = getServiceSupabase()

    // Check if email already exists
    const { data: existing } = await supabase
      .from("delegates")
      .select("delegate_id, id, payment_status")
      .eq("email", email.toLowerCase().trim())
      .maybeSingle()

    // If a pending record exists, return the existing one (resume flow)
    if (existing) {
      if (existing.payment_status === "verified") {
        return NextResponse.json(
          { error: "This email has already been registered and verified." },
          { status: 409 }
        )
      }
      // Resume: return the existing delegate_id so user can continue payment
      return NextResponse.json(
        { delegate_id: existing.delegate_id, id: existing.id },
        { status: 200 }
      )
    }

    // Insert new record — delegate_id is auto-generated by DB trigger
    const { data, error } = await supabase
      .from("delegates")
      .insert({
        name: name.trim(),
        email: email.toLowerCase().trim(),
        phone: phoneClean,
        institution: institution.trim(),
        committee_pref: committee_pref.trim(),
        country_pref: country_pref.trim(),
        payment_status: "pending",
      })
      .select("delegate_id, id")
      .single()

    if (error) {
      console.error("Supabase insert error:", error)

      // Handle unique constraint violation on email
      if (error.code === "23505") {
        return NextResponse.json(
          { error: "This email is already registered." },
          { status: 409 }
        )
      }

      return NextResponse.json({ error: "Failed to create registration." }, { status: 500 })
    }

    return NextResponse.json(data, { status: 201 })
  } catch (err) {
    console.error("Registration API error:", err)
    return NextResponse.json({ error: "Internal server error." }, { status: 500 })
  }
}
